/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "api_constants.h"

namespace org { namespace example { namespace msgrpc { namespace thrift {

const apiConstants g_api_constants;

apiConstants::apiConstants() {
}

}}}} // namespace

